version: '3'
services:
  php:
    image: registry.cn-hangzhou.aliyuncs.com/ywimg/satisfy-php-main:20240506-2
    container_name: satisfy_php
    working_dir: /var/www/html
    ports:
      - "${APP_PORT:-8000}:80"
    volumes:
      - .:/var/www/html
      - ./docker/php/unit.json:/docker-entrypoint.d/config.json
      - /var/www/.composer
    environment:
      APP_ENV: ${APP_ENV:-dev}
      APP_DEBUG: ${APP_DEBUG:-1}
      APP_PATH: /var/www/html
      COMPOSER_HOME: /var/www/.composer
